[package]
name = "rt-one-weekend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.10.0"
rand = "0.9.1"
image = { version = "0.25.6", features = ["rayon"] }
